language: java
sudo: true
dist: trusty
jdk:
- oraclejdk11
before_install:
- chmod +x mvnw
addons:
  sonarcloud:
    organization: cattle-control
    token:
      secure: 0pJnDshTRJQ3p0nejO40LGb+nR07RfH/PugMdxyJQ7VAY1ne76WGOY0Tn4EVGpFguYybAkiYJpsKLmD7/DbyoIjkBGY7+iIiMhq3xx24n8thYoYW2L0jg6NudhmLB7xkdktJOxskiQHVGKQj+H4+c/fCV+4TEq4mTiR1z04AOk0gYa1QN0Ogt+2znZjPr4VGxDDOGoi7WHS9sbJ51kGj8lT4X3oGciAD3aVwu4oVDCrMJxOaJOUpEPsaOSKeEr+DGVgkhxt+bAueQhHF1LUPMXflZnk1L28tf4WZv79KUCClhel7F+CU84OL9jQ2QqHXUsaqKAXIMk158Q4umLZ0FTbwCdL47V36gkIgR/RYKVg6XNuA5ULVR/Sq1Cycpbn+uZvWie47CKTkpWbvteWmWmzzu/GP0cM6ADnkxU/kqV5Ix8RlIBwMpC11hyzWUF4vixqEvoeWlKRNfK6Az5ZOcXVuJawwh7rHcW7Gc5T25Fy6owQsbEp48IeO9E7IIQS4VyqxUuoKzj9Abg3hoIyVIvQrqDN7bTFqtQu8MMvA1dB5p4fpQcyv+jG3g0ra6vQnuolvDroqPe+lCDSstUqdq6r7Se910S+HeMyNYErIx4sHFg0k2ImlqSvcvNQcmu/5BQwhBfKYtkR8jtOq4lIGge6DUn3qXL/idCJWufdnbGo=
script:
  - sonar-scanner
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: thoTTUtqSf8sVPE+rPO/TyagsS/gbowY003wszJeBpYBMeGi/ah/faLumb5ppDFyA+3hnraLqly5FXZm2081HRJ7+S6/ZkByTZw+3mh5z0lecL0bHmCvV5yrneVxqGPkTMPq/LCwkTVd3gXyqAuGiwu+xBIcRdIXaZRPazW+lVJZYAQ23C5KmvZmYI6eDVmbgiy2fXMXHKNwFU+Ef38J9O28T3QQS8hI/+dVU28LQZpWS/8dB726NoCZnzgGk9A00ENGWvTiMqyuz0NVoRNvDDT7/LS7adW73llCTiNvAyYiQ2+r6sWRA+reOhp6Qcm3Cm5zKIMY7uHzV7qRyAtP24M/rPsYt/BmFY99olMIol9dVCrhzvhhNHzo7kUFXuZnmqkBM5P4IM6TmhyJH2Kt82M0X3Drj/Qyi48Vu0QNCuHyrQ8O70WkfvVPCCF+VwAYZ/JkHYIVibSi3o03lLllT+fYBa50gtDV1xK39v+NBnOktjfLYQ+Bed56npPqFPvJLPN7aAPzsBIgRIRxHzuCvKXRMy4LYCeFyTY4iphy0KoGIfLtx6gKy45t6rGSpe5E/osdO53HDwwWfmoJXkfbfYPKNREhcigv1/CEP7SYDjoIHI//11wn/DXJglNamJfiNe9DFTaGOAVWkEiORbcZgh8W9DaPZbwYjzT4F0fRMv8=
  app: cattle-control
  on:
    repo: hmarcuzzo/cattle_control
after_success:
- bash <(curl -s https://codecov.io/bash)
    