language: java
sudo: true
dist: trusty
jdk:
- oraclejdk11
before_install:
- chmod +x mvnw
addons:
  code_climate:
    repo_token:
      secure: "Cx1YVsgscSt/3veuGg2OACDkmeuXbqjke6V/CKftx+qn+5E1e1lRS5X+5wmKA1vO21gj9Ya8IHryIp7KajO+a5InVhpTXAZnxa4z+jgMvCBnrsF16XvPw3+RihMTR+KBJGsI3S6SHZsIn1hg+kCtXy5MjV+muVpmFAmIJrRp5KmQGecIbdNBK83GkvYwzwQeI2KNY+OqVDPjVqH8y3JwcB6KsCj7qdBY3mrMc/Uza1kFrYY/g2F50XAVqttRrf6Glu+qDCivXynPI/KpQBrSK8bmLB3ukO4MXjsxYyWdvJXVS+4u9HZyxO+y/6xnlwd2AOmghf+V6SfNzUL4XdOTcCcVMd27Sn/078jZqlimkpjtMEYt+5XpUQpoGDscK/+5iCO+cJWmfijqgcnUcxtTzRrzg7TnRjIUX5hkzIhHByMmGegjFQIrCyjruJ5kFN+A1UJVAMHP1lBltYGJcSvrRLL2Amhm0hAe6u9n0zVqY6Ku0hbeFeEa2Cj2TS7c1HAfLhakWaxdAeCBBuBwVv5zBkjUR6qfvaepDaIMvo1h4vlmsqvoHjQi7qrm2poPMCwQGucaiVPF/tWw8bicg7lG1XhA9B5gOkKBVx8Rn5UTf0HRfZhTkiTCu0oMGfjQy8z2zU6ZMV1Y7qJ28SXc3AnLXvu+b2b5OUONTVSOmu99w/I="
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mvn test
after_script:
  - ./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml
  - ./cc-test-reporter upload-coverage -d
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: thoTTUtqSf8sVPE+rPO/TyagsS/gbowY003wszJeBpYBMeGi/ah/faLumb5ppDFyA+3hnraLqly5FXZm2081HRJ7+S6/ZkByTZw+3mh5z0lecL0bHmCvV5yrneVxqGPkTMPq/LCwkTVd3gXyqAuGiwu+xBIcRdIXaZRPazW+lVJZYAQ23C5KmvZmYI6eDVmbgiy2fXMXHKNwFU+Ef38J9O28T3QQS8hI/+dVU28LQZpWS/8dB726NoCZnzgGk9A00ENGWvTiMqyuz0NVoRNvDDT7/LS7adW73llCTiNvAyYiQ2+r6sWRA+reOhp6Qcm3Cm5zKIMY7uHzV7qRyAtP24M/rPsYt/BmFY99olMIol9dVCrhzvhhNHzo7kUFXuZnmqkBM5P4IM6TmhyJH2Kt82M0X3Drj/Qyi48Vu0QNCuHyrQ8O70WkfvVPCCF+VwAYZ/JkHYIVibSi3o03lLllT+fYBa50gtDV1xK39v+NBnOktjfLYQ+Bed56npPqFPvJLPN7aAPzsBIgRIRxHzuCvKXRMy4LYCeFyTY4iphy0KoGIfLtx6gKy45t6rGSpe5E/osdO53HDwwWfmoJXkfbfYPKNREhcigv1/CEP7SYDjoIHI//11wn/DXJglNamJfiNe9DFTaGOAVWkEiORbcZgh8W9DaPZbwYjzT4F0fRMv8=
  app: cattle-control
  on:
    repo: hmarcuzzo/cattle_control
after_success:
- bash <(curl -s https://codecov.io/bash)
    